mybatis-plus:
  type-aliases-package: com.laoliu.mp.entity
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    全局的配置<局部表的配置.如果局部表配置了,则全局配置无效,以局部表为准
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null