spring.application.name=MybatisPlusLearning
spring.datasource.url=jdbc:mysql://localhost:3306/mybatis_plus?rewriteBatchedStatements=true&useUnicode=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Lcy10194815!
logging.level.com.laoliu.mp = debug