spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
        client-ip: host.docker.internal
    gateway:
      routes:
#        这里的ID填写路由的ID，必须唯一
        - id: connect
#          这里的uri的lb后面的服务名，必须和nacos中的服务名一致
          uri: lb://connect
          filters:
#           这里的意思是添加请求头X-Request-Id，值为一个随机的UUID
            - AddRequestHeader=X-Request-Id,${random.uuid}
          predicates:
            - Path=/byIDs/**
        - id: connected
          uri: lb://connected
          predicates:
            - Path=/message/**
#      default-filters:
#       这里的意思是添加响应头X-Response-Time，值为当前时间,而且是为所有请求添加的
#        - AddResponseHeader=X-Response-Time,#{T(System).currentTimeMillis()}


server:
  port: 9090